name: Test-Contracts

on:
  push:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install truffle and run tests
        run: |
          npm install truffle -g
          truffle test